### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriella439** [erochest/castle#3]
`errors-2.0` will be switching to use `ExceptT` instead of `EitherT`.  If that will break your package, then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by erochest** [comment]
This is perhaps the one project I'm not using errors on (at least not directly).

**Comment by Gabriel439** [comment]
Oh, in that case just update Hackage when you get a chance.  There is no hurry as I'm a few weeks out from uploading `errors-2.0` to Hackage

**Comment by erochest** [comment]
Will do. Thanks!

I think I originally included it in the list of dependencies, but cleaned the cabal file up after I uploaded it.
